name: Documentation Issue
description: Report missing, incorrect, or unclear documentation.
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for documentation problems or improvements.

        Documentation index:
        - [Docs Overview](https://github.com/bridgelet-org/bridgelet#documentation)
        - [Getting Started](https://github.com/bridgelet-org/bridgelet/blob/main/docs/getting-started.pdf)
        - [Integration Guide](https://github.com/bridgelet-org/bridgelet/blob/main/docs/integration-guide.pdf)

        Example: "Getting Started guide references an outdated SDK name"
  - type: textarea
    id: location
    attributes:
      label: Doc Location
      description: Where is the doc issue? Provide a link or file path.
      placeholder: "docs/getting-started.pdf (Section: Setup)"
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What is wrong or missing?
      placeholder: Describe the documentation issue clearly.
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: What should the documentation say instead?
      placeholder: Provide a corrected statement or new section outline.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any extra context or links?
      placeholder: Add screenshots or references if helpful.
    validations:
      required: false
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What would make this documentation issue resolved?
      placeholder: |
        - The incorrect section is updated.
        - The change is reflected in the PDF or doc source.
    validations:
      required: true
