name: Question / Support
description: Ask a question or get help using Bridgelet.
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for questions or support requests.

        Helpful docs:
        - [Getting Started](https://github.com/bridgelet-org/bridgelet/blob/main/docs/getting-started.pdf)
        - [Integration Guide](https://github.com/bridgelet-org/bridgelet/blob/main/docs/integration-guide.pdf)
        - [Use Cases & Examples](https://github.com/bridgelet-org/bridgelet/blob/main/docs/use-cases.pdf)

        Example: "How do I retry a claim without creating a new ephemeral account?"
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What do you need help with?
      placeholder: Ask your question clearly and concisely.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to achieve and what have you tried?
      placeholder: Include relevant snippets, configurations, or links.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide relevant environment details if applicable.
      placeholder: |
        - OS:
        - Node.js:
        - SDK/Package version:
        - Network (testnet/mainnet):
    validations:
      required: false
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What would make this question resolved for you?
      placeholder: |
        - I can complete the flow without errors.
        - The correct configuration is identified.
    validations:
      required: true
